<a href="https://colab.research.google.com/github/Ravindrakumarnayak/python_practice_daywise/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#numpy is 50 times fastest in array formation infront of python

In [2]:
import numpy as np

In [6]:
a1=np.array([1,2,3,4,55,66]) # 1d array
a1

array([ 1,  2,  3,  4, 55, 66])

In [7]:
a2=np.array([[1,2,3,4,55,66],[1,22,33,44,55,77]]) # 2d array
a2

array([[ 1,  2,  3,  4, 55, 66],
       [ 1, 22, 33, 44, 55, 77]])

In [8]:
np.array(1) #0d array

array(1)

In [9]:
a1=[1,2,3,4]
a2=[1,2,3,4]
a1+a2

[1, 2, 3, 4, 1, 2, 3, 4]

In [10]:
a1=np.array([1,2,3,4])
a2=np.array([1,2,3,4])
a1+a2

array([2, 4, 6, 8])

In [11]:
a1=np.array([1,2,3,4])
a2=np.array([1,2,3,4])
a1-a2

array([0, 0, 0, 0])

In [12]:
a1=np.array([1,2,3,4])
a2=np.array([1,2,3,4])
a1*a2

array([ 1,  4,  9, 16])

In [13]:
a1=np.array([1,2,3,4])
a2=np.array([1,2,3,4])
a1/a2

array([1., 1., 1., 1.])